.gitignore
dtsse-shared-infrastructure.iml
main.tf

Adds slack-help-bot-cftptl-intsvc-mi to KV read and list

---

grafana.tf

add more views

---

grafana.tf
main.tf
postgres.tf
prod.tfvars
variables.tf

Deploy the KV to prod but not grafana and postgres

---

postgres.tf

Fix tf for conditional fw rules on pgsql

---

postgres.tf

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

investigate TF issues

---

postgres.tf

Created DTSSE-3304 to cover the tech debt to shift to using private end point once supported by Azure.
```
[ ] Yes
[x] No
```

Public access and fw rules

---

postgres.tf

Install hypopg extension

---

postgres.tf

These are needed for the migration script to work
```
[ ] Yes
[x] No
```

allow plpgsql, pg_stat_statements, pg_buffercache

---

postgres.tf

Use flexible db

---

postgres.tf

DB data migrated, app and grafana using the flexi db
```
[ ] Yes
[x] No
```

Removes sinigle Postgres instance

---

postgres.tf

Remove the private flexible db

---

.github/renovate.json
action-group.tf
budget-alert.tf

Adds an alert when we get to 90% of grafana budget (£500)

---

budget-alert.tf

Commented out the Grafana dimension in an attempt to unblock the CI build-pipeline

Comment out grafana dimension

---

budget-alert.tf

Comment out whole file as part of trial-and-error

Comment out budget-alert

---

budget-alert.tf

Uncommenting as requested

---

budget-alert.tf

Comment out whole file as part of trial-and-error

Change name to grafana-cost-alert

---

budget-alert.tf

Revert change of name

---

budget-alert.tf

Updating contact group

---

budget-alert.tf

Alter start date

---

main.tf

Update secret to use connection string

Update secret to use connection string

---

postgres.tf

Test module changes to see if the tfplan stops trying to destroy pg admins

Test with new module changes

---

variables.tf

"Grafana Name: "dtsse-grafana10-aat"): performing GrafanaCreate: unexpected status 400 (400 Bad Request) with error: ZoneRedundancyNotSupported: Zone redundancy is currently not supported in this region: uksouth. Zone redundancy is supported in the following regions: australiaeast, eastasia, eastus, eastus2euap, northeurope, southcentralus, westus3."
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

Update variables.tf ZoneRedundancy not available in UK South.

---

grafana.tf

See [DTSSE-5305](https://tools.hmcts.net/jira/browse/DTSSE-5305)
Add role definitions to Grafana v10  instance namely Grafana {Admin, Editor, Viewer}

Assign roles assignments to Grafana v10 server

---

grafana.tf

See https://tools.hmcts.net/jira/browse/DTSSE-5305

Correct "Grafana Viewer" role assignment

---

grafana.tf

See https://tools.hmcts.net/jira/browse/DTSSE-5305

Duplicate role assignment and permissions for Grafana v9 and Grafana v10

---

budget-alert.tf

See https://tools.hmcts.net/jira/browse/DTSSE-5305

Fix start date for monthly time grain 2024-09-13

---

budget-alert.tf

See https://tools.hmcts.net/jira/browse/DTSSE-5305

Fix for time_period.0.start_date" must be first of the month, got day 13

---

Jenkinsfile_CNP
aat.tfvars
grafana.tf
main.tf
prod.tfvars
state.tf

See [DTSPO-26592](https://tools.hmcts.net/jira/browse/DTSPO-26592)
Adds prod managed grafana v11 instance
Terraform plan on prod and aat looks good - https://build.hmcts.net/job/HMCTS_d_to_i/job/dtsse-shared-infrastructure/view/change-requests/job/PR-191/13/

chore(prod): enable grafana dashboard v11 on prod

---

grafana.tf
main.tf
postgres.tf
prod.tfvars
variables.tf

See [DTSPO-26592](https://tools.hmcts.net/jira/browse/DTSPO-26592)
Disables public access into prod grafana database

chore: restrict pg db public access on prod

---

prod.tfvars

- grafana managed private endpoint doesn't support flexible postgres servers yet. It supports private links though, so we can use that instead.
See [DTSPO-26592](https://tools.hmcts.net/jira/browse/DTSPO-26592)
Grafana managed private endpoint doesn't support flexible postgres servers yet. It supports private links though, so we can use that instead. This will be looked at via another ticket.

chore: don't restrict pg db public access on prod just yet

---

action-group.tf
data.tf
grafana.tf
main.tf
postgres.tf
private-link.tf
prod.tfvars
provider.tf
state.tf
variables.tf

See [DTSPO-26700](https://tools.hmcts.net/jira/browse/DTSPO-26700)
Adds a private link to the postgres db and links grafana to it

feat: add private link resources

---

aat.tfvars

https://tools.hmcts.net/jira/browse/DTSPO-26964
- Add missing aks_subscription_id to aat.tfvars to fix role assignment error

Patch - Add missing aks_subscription_id to aat.tfvars to fix role assignment error
